name = "sntc-induction-server"
compatibility_date = "2024-07-24"

# [vars]
# MY_VAR = "my-variable"

# [[kv_namespaces]]
# binding = "MY_KV_NAMESPACE"
# id = "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

# [[r2_buckets]]
# binding = "MY_BUCKET"
# bucket_name = "my-bucket"

[[d1_databases]]
binding = "DB"
database_name = "sntc-induction-db"
database_id = "d3c7b4b2-2da8-4e89-ae10-e5d0b184830d"

# [ai]
# binding = "AI"