CREATE TABLE `users` (
    `userId` TEXT NOT NULL PRIMARY KEY,
    `COPS` BOOLEAN DEFAULT 0,
    `theQuantClub` BOOLEAN DEFAULT 0,
    `bizClub` BOOLEAN DEFAULT 0,
    `SAE` BOOLEAN DEFAULT 0,
    `AMC` BOOLEAN DEFAULT 0,
    `astroClub` BOOLEAN DEFAULT 0,
    `csi` BOOLEAN DEFAULT 0
);
